import { parseAbi } from "viem";

export const nostosInstantPoolP6Abi = parseAbi([
  "function asset() view returns (address)",
  "function vault() view returns (address)",
  "function ticket() view returns (address)",
  "function protocolTreasury() view returns (address)",
  "function availableLiquidity() view returns (uint256)",
  "function lpNav() view returns (uint256)",
  "function totalSupply() view returns (uint256)",
  "function sharePrice() view returns (uint256)",
  "function outstandingFaceValue() view returns (uint256)",
  "function outstandingCostBasis() view returns (uint256)",
  "function utilizationBps() view returns (uint256)",
  "function cumulativeGrossSpread() view returns (uint256)",
  "function accruedProtocolFees() view returns (uint256)",
  "function cumulativeProtocolFees() view returns (uint256)",
  "function lpRealizedProfit() view returns (uint256)",
  "function previewDeposit(uint256 assets) view returns (uint256)",
  "function previewRedeem(uint256 shares) view returns (uint256)",
  "function maxRedeem(address user) view returns (uint256)",
  "function withdrawalUnlockAt(address user) view returns (uint64)",
  "function balanceOf(address account) view returns (uint256)",
  "function decimals() view returns (uint8)",
  "function getPricing() view returns (uint256 baseDiscountBps, uint256 utilizationSlopeBps, uint256 sizeSlopeBps, uint256 minDiscountBps, uint256 maxDiscountBps, uint256 maxUtilizationBps)",
  "function quoteTicket(uint256 ticketId) view returns (uint256 faceValue, uint256 amountOut, uint256 discountBps, uint256 utilizationBps, uint256 sizeRatioBps, uint256 postTradeUtilizationBps)",
  "function positions(uint256 ticketId) view returns (uint256 ticketId, uint256 requestId, address seller, uint256 faceValue, uint256 costBasis, uint256 discountBps, uint64 acquiredAt, uint64 settledAt, uint8 status)",
  "function deposit(uint256 assets, uint256 minSharesOut) returns (uint256)",
  "function redeem(uint256 shares, uint256 minAssetsOut) returns (uint256)",
  "function sellTicket(uint256 ticketId, uint256 minAmountOut) returns (uint256)",
  "function harvest(uint256 ticketId) returns (uint256)",
]);
