import type { Metadata } from "next";
import { Clock3, Zap } from "lucide-react";
import { AmountForm } from "@/components/product/amount-form";
import { DataPanel, DefinitionRows, ProductPage, StateNotice, TableEmpty } from "@/components/product/product-primitives";
import { PageHeading } from "@/components/ui/page-heading";
import { StatusBadge } from "@/components/ui/status-badge";

export const metadata: Metadata = { title: "Redemptions", description: "Request and track standard settlement or review instant-liquidity eligibility through Nostos." };

export default function RedemptionsPage() {
  return <ProductPage><PageHeading eyebrow="Nostos Queue" title="Your capital is ready to leave." description="Compare the standard settlement path with optional instant liquidity before creating a redemption request." /><div className="mt-8 grid gap-6 lg:grid-cols-2"><DataPanel title="Standard settlement" description="Receive the eligible amount after the underlying settlement completes." aside={<StatusBadge label="Queue path" tone="pending" icon={<Clock3 size={14} aria-hidden="true" />} />}><DefinitionRows rows={[{ label: "Estimate" }, { label: "Discount" }, { label: "Resulting state", value: "Pending after confirmation" }]} /><p className="mt-4 text-xs leading-5 text-muted-foreground">Timing remains an estimate until verified vault terms are loaded.</p></DataPanel><DataPanel title="Instant cashout" description="Sell an eligible pending claim to available liquidity. The discount is the visible cost of speed." aside={<StatusBadge label="Unavailable" tone="neutral" icon={<Zap size={14} aria-hidden="true" />} />}><DefinitionRows rows={[{ label: "Available" }, { label: "Discount" }, { label: "Quote expiry" }, { label: "Pool capacity" }]} /><p className="mt-4 text-xs leading-5 text-muted-foreground">Instant cashout is shown only after a pending claim exists and a verified quote is available.</p></DataPanel></div><DataPanel className="mt-6" title="Request redemption" description="A connected position and verified vault terms are required before a request can be submitted."><AmountForm purpose="redemption" assetLabel="Vault share amount" actionLabel="Request unavailable" /></DataPanel><div className="mt-6 grid gap-4 md:grid-cols-2"><StateNotice title="No instant liquidity" message="Keep the standard settlement path or check again after pool capacity is connected." /><StateNotice title="Quote expired" message="Expired quotes cannot be confirmed. A future connected flow will require a fresh quote with current pricing and capacity." /></div><DataPanel className="mt-6" title="Your requests" description="Request IDs and settlement states will be read from the connected wallet."><TableEmpty columns={["Request", "Vault", "Path", "Estimate", "State", "Next action"]} title="No requests to show" message="Connect a wallet to view its redemption records. No sample requests are displayed." /></DataPanel></ProductPage>;
}
