"use client";
import Link from "next/link";
import { ChevronRight, Menu, X } from "lucide-react";
import { usePathname } from "next/navigation";
import { useState, type ReactNode } from "react";
import { BrandMark } from "@/components/shell/brand-mark";
import { WalletPreviewDialog } from "@/components/shell/wallet-preview-dialog";
import { Container } from "@/components/ui/container";
const items = [{ href: "/explore", label: "Explore" }, { href: "/portfolio", label: "Portfolio" }, { href: "/redemptions", label: "Redemptions" }, { href: "/pool", label: "Instant pool" }, { href: "/registry", label: "Registry" }];
function Navigation({ mobile = false, close }: { mobile?: boolean; close?: () => void }) { const pathname = usePathname(); return <nav className={mobile ? "mt-12 space-y-1" : "mt-5 space-y-1"} aria-label={mobile ? "Mobile product navigation" : "Product navigation"}>{items.map((item) => <Link key={item.href} href={item.href} onClick={close} className={`flex min-h-11 items-center justify-between rounded-control px-3 text-sm font-semibold transition-colors ${pathname === item.href || pathname.startsWith(`${item.href}/`) ? "bg-[var(--ink)] text-white" : "hover:bg-black/[.05]"}`}>{item.label}<ChevronRight size={16} aria-hidden="true" /></Link>)}</nav>; }
export function ProductShell({ children }: { children: ReactNode }) { const [open, setOpen] = useState(false); return <div className="min-h-screen bg-[#fbfaf8]"><a className="skip-link" href="#main-content">Skip to content</a><aside className="fixed inset-y-0 left-0 z-30 hidden w-64 border-r border-[var(--line)] bg-white p-6 lg:block"><BrandMark /><p className="eyebrow mt-12 text-muted-foreground">Nostos workspace</p><Navigation /><div className="absolute inset-x-6 bottom-6"><WalletPreviewDialog className="w-full" /></div></aside><div className="lg:pl-64"><header className="sticky top-0 z-20 border-b border-[var(--line)] bg-white/95 backdrop-blur"><Container className="flex min-h-20 items-center justify-between gap-4"><button className="inline-flex min-h-11 min-w-11 items-center justify-center rounded-control border border-[var(--line-strong)] lg:hidden" onClick={() => setOpen(true)} aria-label="Open product navigation"><Menu size={18} /></button><div className="lg:hidden"><BrandMark /></div><div className="hidden text-sm text-muted-foreground lg:block">Nostos workspace</div><WalletPreviewDialog className="hidden sm:inline-flex" /></Container></header>{open && <div className="fixed inset-0 z-40 lg:hidden"><button className="absolute inset-0 bg-[rgba(16,16,16,.55)]" aria-label="Close product navigation" onClick={() => setOpen(false)} /><aside className="absolute inset-y-0 left-0 w-[min(84vw,320px)] bg-white p-6 shadow-[8px_0_0_var(--ink)]"><div className="flex items-center justify-between"><BrandMark /><button className="inline-flex min-h-11 min-w-11 items-center justify-center rounded-control border border-[var(--line)]" onClick={() => setOpen(false)} aria-label="Close product navigation"><X size={18} /></button></div><Navigation mobile close={() => setOpen(false)} /><div className="mt-8"><WalletPreviewDialog className="w-full" /></div></aside></div>}<main id="main-content" className="min-h-[calc(100vh-80px)]">{children}</main></div></div>; }
